name: 'ga4_attribution_models'
version: '1.0.0'
config-version: 2

profile: 'ga4_attribution_models'

model-paths: ["attribution_models", "ecommerce_funnel", "user_journey", "utils"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

vars:
  ga4_project: 'your-gcp-project'
  ga4_dataset: 'your-ga4-dataset'
