dataformCoreVersion: "3.0.20"
defaultProject: marketing data analyst
defaultLocation: EU
defaultDataset: attribution_models
defaultAssertionDataset: attribution_assertions
vars:
  start_date: "20210101"
  end_date: "20210131"
  ga4_project: "bigquery-public-data"
  ga4_dataset: "ga4_obfuscated_sample_ecommerce"
  lookback_days: 30
