dataformCoreVersion: "3.0.55"
defaultProject: marketingdataanalyst
defaultLocation: US
defaultDataset: attribution_models
defaultAssertionDataset: attribution_assertions
vars:
  start_date: "20201101"
  end_date: "20201220"
  ga4_project: "bigquery-public-data"
  ga4_dataset: "ga4_obfuscated_sample_ecommerce"
  lookback_days: "30"
  source_extraction_mode: "auto"
  exclude_modeled_events: "false"
